package edu.ucne.gymapp.presentation.workoutexercises

import edu.ucne.gymapp.data.local.entities.WorkoutExercise

data class WorkoutExerciseUiState(
    val workoutId: Int = 0,
    val exerciseId: Int = 0,
    val order: Int = 1,
    val plannedSets: Int = 3,
    val completedSets: Int = 0,
    val status: String = "PENDING", // PENDING, IN_PROGRESS, COMPLETED, SKIPPED
    val startTime: Long? = null,
    val endTime: Long? = null,
    val notes: String? = null,
    val workoutExercises: List<WorkoutExercise> = emptyList(),
    val selectedWorkoutExercise: WorkoutExercise? = null,
    val activeWorkoutExercises: List<WorkoutExercise> = emptyList(),
    val completedWorkoutExercises: List<WorkoutExercise> = emptyList(),
    val pendingWorkoutExercises: List<WorkoutExercise> = emptyList(),
    val exercisesInWorkout: List<WorkoutExercise> = emptyList(),
    val currentExerciseIndex: Int = 0,
    val totalExercises: Int = 0,
    val isLastExercise: Boolean = false,
    val isFirstExercise: Boolean = true,
    val exerciseProgress: Float = 0f,
    val workoutProgress: Float = 0f,
    val exerciseTimer: Long = 0,
    val isExerciseActive: Boolean = false,
    val currentSet: Int = 1,
    val restTimer: Long = 0,
    val isResting: Boolean = false,
    val selectedStatus: String = "",
    val isLoading: Boolean = false,
    val errorMessage: String? = null,
    val successMessage: String? = null,
    val isCreated: Boolean = false,
    val isUpdated: Boolean = false,
    val isDeleted: Boolean = false,
    val exerciseStarted: Boolean = false,
    val exerciseCompleted: Boolean = false,
    val exerciseSkipped: Boolean = false,
    val setCompleted: Boolean = false,
    val movedToNext: Boolean = false,
    val movedToPrevious: Boolean = false
)
